const CRISIS_KEYWORDS: readonly string[] = [
  "bunuh diri",
  "mengakhiri hidup",
  "gak mau hidup",
  "nggak mau hidup",
  "pengen mati",
  "mau mati",
  "ingin mati",
  "nyakitin diri",
  "self harm",
  "lebih baik mati",
  "mending mati",
  "akhiri semua",
  "putus asa",
  "gak ada harapan",
  "nggak ada harapan",
  "hidup gak ada gunanya",
  "ngga mau lanjut",
  "gak mau lanjut",

  "kill myself",
  "end my life",
  "want to die",
  "want to suicide",
  "suicide",
  "cut myself",
  "no reason to live",
  "better off dead",
  "end it all",
  "don't want to live",
  "dont want to live",

  "自殺",
  "死にたい",
  "命を ended",
  "自分を傷つけ",
  "消えたい",
  "生きる意味",

  "自杀",
  "想死",
  "结束生命",
  "自残",
  "不想活",
  "活不下去",

  "suicidio",
  "querer morir",
  "matarme",
  "quitarme la vida",
  "autodaño",
  "no quiero vivir",

  "suicide",
  "mourir",
  "me tuer",
  "finir ma vie",
  "autodestruction",
  "je veux mourir",

  "انتحار",
  "أريد أن أموت",
  "أريد الموت",
  "إنهاء حياتي",
  "أ不想 حياة",

  "자살",
  "죽고싶",
  "죽고 싶",
  "살기 싫",
  "내 목숨",
  "자해",

  "suicídio",
  "quero morrer",
  "me matar",
  "acabar com minha vida",
  "não quero viver",

  "selbstmord",
  "sterben wollen",
  "mich umbringen",
  "leben beenden",
  "nicht leben wollen",
];

export function detectCrisisKeywords(text: string): boolean {
  const lower = text.toLowerCase();
  return CRISIS_KEYWORDS.some((kw) => lower.includes(kw));
}
